config/routes.rb
Rails.application.routes.draw do

  root 'pins#index'

  resources :pins
    

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  validates_presence_of :title, :url, :slug, :text, :resource_type
  validates_uniqueness_of :slug
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  
  def index
    @pins = Pin.all
  end
  
  def show
    @pin = Pin.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coder Pinterest</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pins/index.erb
<div class="header">
  <h1>Learning to Code</h1>
  <h3>A Collection of Ruby on Rails Resources for Beginners</h3>
</div>
<hr/>
<div class="pins">
  <% @pins.each_slice(3) do |row| %>
    <div class="row">
      <% row.each do |pin| %>      
        <div class="pin-container col-md-4">
          <div class="pin">
            <div class="pin-header">
              <h4>
                <a href="<%= pin_path(pin) %>">
                  <%= "#{pin.title}" %>
                </a>
              </h4>
              <a class="url" href="<%= "#{pin.url}" %>">
                <%= "#{pin.url}" %>
              </a>
            </div>
            <hr/>
            <p class="text"><%= "#{pin.text}" %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<hr/>

app/views/pins/show.erb
<div class="header">
  <h1>
    <%= "#{@pin.title}" %>
  </h1>
</div>

<div class="show-pin">
  <p><%= "#{@pin.text}" %></p>

  <hr/>
  <p>
    <b>Visit <%= "#{@pin.title}" %> at: </b>
    <a class="url" href="<%= "#{pin.url}" %>" target="_blank">
      <%= "#{pin.url}" %>
    </a>
  </p>
</div>
<br/>
<a href="/">
  Back to Home
</a>